<?php
/**
 * Created by PhpStorm.
 * User: liluoao
 * Date: 2016/3/21
 */
namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use app\common\Common;
use yii\data\Pagination;
use app\models\Contact;

class ContactController extends Controller
{
    public $layout = false;
    public $enableCsrfValidation = false;

    /*
    * @function 权限验证
    * @date 2016-4-17
    */
    public function beforeAction($action)
    {
        if(is_null(yii::$app->session['username']) || yii::$app->session['userType'] != '2')
        {
            $this->redirect(['login/index']);

            return false;
        }else{
            return parent::beforeAction($action); // TODO: Change the autogenerated stub

        }
    }


    public function actionList()
    {
        return $this->render('list');
    }

    /*
     * 留言列表页
     */
    public function actionListall(){
        $date1 = Yii::$app->request->get('_senderDateTime');
        $data2 = Yii::$app->request->get('senderDateTime_');
        $para=array();
        $para['date1'] = $date1;
        $para['data2'] = $data2;
        $whereStr = '1=1';//查询条件
        if ($date1 != '') {
            $whereStr = $whereStr . " and createDateTime >= '" . $date1 . "%'";
        }
        if ($data2 != '') {
            $whereStr = $whereStr . " and createDateTime <= '" . $data2 . "%'";
        }
        $contacts = Contact::find()->where($whereStr);
        $pages = new Pagination(['totalCount' =>$contacts->count(), 'pageSize' => Common::PAGESIZE]);//分页
        $models = $contacts->offset($pages->offset)->limit($pages->limit)->orderBy('createDateTime DESC')->all();

        return $this->render('listall',[
            'contacts' => $models,
            'pages' => $pages,
            'para' => $para,
        ]);
    }

    /*
     * 单个删除
     */
    public function actionDelete(){
        $id = Yii::$app->request->post("id");
        $contact = Contact::findOne($id);
        if($contact->delete()){
            return "success";
        }else{
            return "fail";
        }
    }

    /*
     * 多选删除
     */
    public function actionDeleteall()
    {
        $ids = Yii::$app->request->post("ids");
        $ids_array = explode('-',$ids);
        foreach($ids_array as $key => $data){
            Contact::deleteAll('id = :id',[':id'=>$data]);
        }
        return 'success';
    }

}
